


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Cohorts" (
    "year" smallint NOT NULL,
    "term" character varying NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL,
    CONSTRAINT "cohorts_term_check" CHECK ((("term")::"text" = ANY ((ARRAY['Fall'::character varying, 'Spring'::character varying, 'Summer'::character varying, 'Winter'::character varying])::"text"[])))
);


ALTER TABLE "public"."Cohorts" OWNER TO "postgres";


COMMENT ON TABLE "public"."Cohorts" IS 'e.g. Fall 2025, Spring 2023, etc.';



ALTER TABLE "public"."Cohorts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Cohorts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Roles" (
    "name" character varying NOT NULL,
    "type" character varying NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL,
    CONSTRAINT "roles_type_check" CHECK ((("type")::"text" = ANY ((ARRAY['prior'::character varying, 'current'::character varying, 'future_interest'::character varying])::"text"[])))
);


ALTER TABLE "public"."Roles" OWNER TO "postgres";


ALTER TABLE "public"."Roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" character varying,
    "role" character varying
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


COMMENT ON TABLE "public"."Users" IS 'Users of app (can be either user, staff, or admin)';



CREATE TABLE IF NOT EXISTS "public"."VolunteerCohorts" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "cohort_id" bigint NOT NULL,
    "volunteer_id" bigint NOT NULL
);


ALTER TABLE "public"."VolunteerCohorts" OWNER TO "postgres";


COMMENT ON TABLE "public"."VolunteerCohorts" IS 'Relation between Volunteers and Cohorts';



CREATE TABLE IF NOT EXISTS "public"."VolunteerRoles" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role_id" bigint NOT NULL,
    "volunteer_id" bigint NOT NULL
);


ALTER TABLE "public"."VolunteerRoles" OWNER TO "postgres";


COMMENT ON TABLE "public"."VolunteerRoles" IS 'Relation between Volunteers and Roles';



CREATE TABLE IF NOT EXISTS "public"."Volunteers" (
    "name_org" character varying NOT NULL,
    "pseudonym" character varying,
    "pronouns" character varying,
    "email" character varying,
    "phone" character varying,
    "position" character varying,
    "opt_in_communication" boolean DEFAULT true,
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id" bigint NOT NULL,
    CONSTRAINT "volunteers_position_check" CHECK ((("position")::"text" = ANY ((ARRAY['member'::character varying, 'volunteer'::character varying, 'staff'::character varying])::"text"[])))
);


ALTER TABLE "public"."Volunteers" OWNER TO "postgres";


ALTER TABLE "public"."Volunteers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Volunteers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Cohorts"
    ADD CONSTRAINT "Cohorts_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Cohorts"
    ADD CONSTRAINT "Cohorts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Roles"
    ADD CONSTRAINT "Roles_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Roles"
    ADD CONSTRAINT "Roles_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."Roles"
    ADD CONSTRAINT "Roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."VolunteerCohorts"
    ADD CONSTRAINT "VolunteerCohorts_pkey" PRIMARY KEY ("cohort_id", "volunteer_id");



ALTER TABLE ONLY "public"."VolunteerRoles"
    ADD CONSTRAINT "VolunteerRoles_pkey" PRIMARY KEY ("role_id", "volunteer_id");



ALTER TABLE ONLY "public"."Volunteers"
    ADD CONSTRAINT "Volunteers_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Volunteers"
    ADD CONSTRAINT "Volunteers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."VolunteerCohorts"
    ADD CONSTRAINT "VolunteerCohorts_cohort_id_fkey" FOREIGN KEY ("cohort_id") REFERENCES "public"."Cohorts"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."VolunteerCohorts"
    ADD CONSTRAINT "VolunteerCohorts_volunteer_id_fkey" FOREIGN KEY ("volunteer_id") REFERENCES "public"."Volunteers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."VolunteerRoles"
    ADD CONSTRAINT "VolunteerRoles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."Roles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."VolunteerRoles"
    ADD CONSTRAINT "VolunteerRoles_volunteer_id_fkey" FOREIGN KEY ("volunteer_id") REFERENCES "public"."Volunteers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."Cohorts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Roles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."VolunteerCohorts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."VolunteerRoles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Volunteers" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "full permission for development phase" ON "public"."Cohorts" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "full permission for development phase" ON "public"."Roles" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "full permission for development phase" ON "public"."VolunteerCohorts" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "full permission for development phase" ON "public"."VolunteerRoles" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "full permissions for development phase" ON "public"."Volunteers" TO "anon" USING (true) WITH CHECK (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Cohorts" TO "anon";
GRANT ALL ON TABLE "public"."Cohorts" TO "authenticated";
GRANT ALL ON TABLE "public"."Cohorts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Cohorts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Cohorts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Cohorts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Roles" TO "anon";
GRANT ALL ON TABLE "public"."Roles" TO "authenticated";
GRANT ALL ON TABLE "public"."Roles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Roles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON TABLE "public"."VolunteerCohorts" TO "anon";
GRANT ALL ON TABLE "public"."VolunteerCohorts" TO "authenticated";
GRANT ALL ON TABLE "public"."VolunteerCohorts" TO "service_role";



GRANT ALL ON TABLE "public"."VolunteerRoles" TO "anon";
GRANT ALL ON TABLE "public"."VolunteerRoles" TO "authenticated";
GRANT ALL ON TABLE "public"."VolunteerRoles" TO "service_role";



GRANT ALL ON TABLE "public"."Volunteers" TO "anon";
GRANT ALL ON TABLE "public"."Volunteers" TO "authenticated";
GRANT ALL ON TABLE "public"."Volunteers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Volunteers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Volunteers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Volunteers_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

alter table "public"."Cohorts" drop constraint "cohorts_term_check";

alter table "public"."Roles" drop constraint "roles_type_check";

alter table "public"."Volunteers" drop constraint "volunteers_position_check";

alter table "public"."Cohorts" add constraint "cohorts_term_check" CHECK (((term)::text = ANY ((ARRAY['Fall'::character varying, 'Spring'::character varying, 'Summer'::character varying, 'Winter'::character varying])::text[]))) not valid;

alter table "public"."Cohorts" validate constraint "cohorts_term_check";

alter table "public"."Roles" add constraint "roles_type_check" CHECK (((type)::text = ANY ((ARRAY['prior'::character varying, 'current'::character varying, 'future_interest'::character varying])::text[]))) not valid;

alter table "public"."Roles" validate constraint "roles_type_check";

alter table "public"."Volunteers" add constraint "volunteers_position_check" CHECK ((("position")::text = ANY ((ARRAY['member'::character varying, 'volunteer'::character varying, 'staff'::character varying])::text[]))) not valid;

alter table "public"."Volunteers" validate constraint "volunteers_position_check";


